spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account_service?ApplicationName=TestSweetApp
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

classifier_currency_url : http://localhost:8081/api/classifier/close/currency/
classifier_category_url : http://localhost:8081/api/classifier/close/operation/