spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scheduler?ApplicationName=TestSweetApp
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
      platform: postgres
    properties:
      "org.quartz.jobStore.driverDelegateClass": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
      "org.quartz.jobStore.tablePrefix" : "quartz.QRTZ_"
server:
  port : 8082

account_url : http://localhost:8080/api/account/
account_backend_url : http://account-service:8080/backend/account

classifier_currency_url : http://localhost:8081/api/classifier/close/currency/
classifier_category_url : http://localhost:8081/api/classifier/close/operation/