spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scheduler?ApplicationName=TestSweetApp
    username: postgres
    password: postgres
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
      platform: postgres
    properties:
      "org.quartz.jobStore.driverDelegateClass": "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
      "org.quartz.jobStore.tablePrefix" : "quartz.QRTZ_"
server:
  port : 8082